import { PrismaClient } from '@prisma/client';
import { seedWorkers } from './seed-workers';
import { seedSuppliers } from './seed-suppliers';
import { seedSubcontractors } from './seed-subcontractors';

const prisma = new PrismaClient();

export async function seedDemoData() {
  console.log('--- STARTING DEMO DATA SEED ---');
  
  // 1. Base master data
  console.log('Seeding Master Data...');
  await seedWorkers();
  await seedSuppliers();
  await seedSubcontractors();

  const superAdmin = await prisma.user.findFirst({ where: { role: 'SUPER_ADMIN' } });
  if (!superAdmin) {
    console.warn('No SUPER_ADMIN found. Skipping transaction seeding.');
    return;
  }

  const suppliers = await prisma.supplier.findMany({ take: 3 });
  const subcontractors = await prisma.subcontractor.findMany({ take: 2 });
  const workers = await prisma.worker.findMany({ take: 10 });

  // 2. Demo Project
  console.log('Seeding Project...');
  const project = await prisma.project.create({
    data: {
      name: 'Demo Commercial Building',
      description: 'A sample project generated by Master Reset',
      location: '123 Demo St, Business City',
      status: 'ONGOING',
      contractAmount: 2940000.00,
      client: 'Demo Corp Ltd.',
      startDate: new Date(),
      endDate: new Date(new Date().setMonth(new Date().getMonth() + 6)),
      managerId: superAdmin.id,
    }
  });

  // 3. Awarded & Consolidated BOQ Items
  console.log('Seeding BOQ...');
  const boq1 = await prisma.awardedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'CONC-001',
      description: 'Ready Mix Concrete 3000 PSI',
      unit: 'cu.m',
      quantity: 500,
      directCost: 3500,
      indirectCost: 500,
      combinedUnitCost: 4000,
      totalCost: 2000000,
      status: 'APPROVED',
      processingType: 'MATERIAL_EQUIPMENT'
    }
  });

  const cBoq1 = await prisma.consolidatedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'CONC-001',
      description: 'Concrete Materials',
      unit: 'cu.m',
      quantity: 500,
      unitCost: 4000,
      totalCost: 2000000,
    }
  });

  const boq2 = await prisma.awardedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'REB-002',
      description: 'Reinforcing Steel Bars Grade 40',
      unit: 'kg',
      quantity: 10000,
      directCost: 60,
      indirectCost: 10,
      combinedUnitCost: 70,
      totalCost: 700000,
      status: 'APPROVED',
      processingType: 'MATERIAL_EQUIPMENT'
    }
  });

  const cBoq2 = await prisma.consolidatedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'REB-002',
      description: 'Steel Rebars',
      unit: 'kg',
      quantity: 10000,
      unitCost: 70,
      totalCost: 700000,
    }
  });

  const boq3 = await prisma.awardedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'FORM-003',
      description: 'Phenolic Board 1/2"',
      unit: 'pcs',
      quantity: 200,
      directCost: 1000,
      indirectCost: 200,
      combinedUnitCost: 1200,
      totalCost: 240000,
      status: 'APPROVED',
      processingType: 'MATERIAL_EQUIPMENT'
    }
  });

  const cBoq3 = await prisma.consolidatedBOQItem.create({
    data: {
      projectId: project.id,
      itemCode: 'FORM-003',
      description: 'Formworks',
      unit: 'pcs',
      quantity: 200,
      unitCost: 1200,
      totalCost: 240000,
    }
  });

  await prisma.bOQMapping.createMany({
    data: [
      { mappingType: '1_TO_1', awardedBoqItemId: boq1.id, consolidatedBoqItemId: cBoq1.id },
      { mappingType: '1_TO_1', awardedBoqItemId: boq2.id, consolidatedBoqItemId: cBoq2.id },
      { mappingType: '1_TO_1', awardedBoqItemId: boq3.id, consolidatedBoqItemId: cBoq3.id }
    ]
  });

  // 4. Material Request
  console.log('Seeding MRF...');
  const mrf = await prisma.materialRequest.create({
    data: {
      mrNumber: 'MRF-DEMO-001',
      projectId: project.id,
      purpose: 'Initial Foundation Pouring',
      dateNeeded: new Date(new Date().setDate(new Date().getDate() + 7)),
      status: 'APPROVED',
      requesterId: superAdmin.id,
      preparerId: superAdmin.id,
      items: {
        create: [
          { quantity: 100, consolidatedBoqItemId: cBoq1.id },
          { quantity: 5000, consolidatedBoqItemId: cBoq2.id },
          { quantity: 50, consolidatedBoqItemId: cBoq3.id }
        ]
      }
    },
    include: { items: true }
  });

  // 5. Canvass Form
  console.log('Seeding Canvass...');
  if (suppliers.length > 0) {
    const canvass = await prisma.canvassForm.create({
      data: {
        canvassNumber: 'CANV-DEMO-001',
        projectId: project.id,
        mrId: mrf.id,
        status: 'APPROVED',
        preparedById: superAdmin.id,
        items: {
          create: [
            { quantityRequired: 100, consolidatedBoqItemId: cBoq1.id },
            { quantityRequired: 5000, consolidatedBoqItemId: cBoq2.id },
            { quantityRequired: 50, consolidatedBoqItemId: cBoq3.id }
          ]
        }
      },
      include: { items: true }
    });

    await prisma.supplierQuotation.create({
      data: {
        canvassFormId: canvass.id,
        supplierId: suppliers[0].id,
        status: 'AWARDED',
        isRecommended: true,
        items: {
          create: [
            {
              canvassItemId: canvass.items[0].id,
              unitCost: 3400,
              quantityAvailable: 100,
              totalCost: 340000,
              remarks: 'Lowest bidder'
            },
            {
              canvassItemId: canvass.items[1].id,
              unitCost: 65,
              quantityAvailable: 5000,
              totalCost: 325000,
              remarks: 'Discounted rate'
            },
            {
              canvassItemId: canvass.items[2].id,
              unitCost: 1100,
              quantityAvailable: 50,
              totalCost: 55000,
              remarks: 'Available on stock'
            }
          ]
        }
      }
    });

    if (suppliers.length > 1) {
      await prisma.supplierQuotation.create({
        data: {
          canvassFormId: canvass.id,
          supplierId: suppliers[1].id,
          status: 'RECEIVED',
          isRecommended: false,
          items: {
            create: [
              {
                canvassItemId: canvass.items[0].id,
                unitCost: 3500,
                quantityAvailable: 100,
                totalCost: 350000,
              },
              {
                canvassItemId: canvass.items[1].id,
                unitCost: 68,
                quantityAvailable: 5000,
                totalCost: 340000,
              },
              {
                canvassItemId: canvass.items[2].id,
                unitCost: 1150,
                quantityAvailable: 50,
                totalCost: 57500,
              }
            ]
          }
        }
      });
    }

    // 6. Purchase Order
    console.log('Seeding PO...');
    await prisma.purchaseOrder.create({
      data: {
        poNumber: 'PO-DEMO-001',
        supplierId: suppliers[0].id,
        canvassFormId: canvass.id,
        mrId: mrf.id,
        status: 'APPROVED',
        deliveryDate: new Date(new Date().setDate(new Date().getDate() + 7)),
        paymentTermsDays: 30,
        preparerId: superAdmin.id,
        items: {
          create: [
            { consolidatedBoqItemId: cBoq1.id, quantity: 100, unitCost: 3400 },
            { consolidatedBoqItemId: cBoq2.id, quantity: 5000, unitCost: 65 },
            { consolidatedBoqItemId: cBoq3.id, quantity: 50, unitCost: 1100 }
          ]
        }
      }
    });
  }

  // 7. Payroll
  console.log('Seeding Payroll...');
  if (workers.length > 0) {
    const periodEnd = new Date();
    const periodStart = new Date(new Date().setDate(new Date().getDate() - 14));
    
    const payrollPeriod = await prisma.payrollPeriod.create({
      data: {
        month: periodStart.getMonth() + 1,
        year: periodStart.getFullYear(),
        periodType: 'REGULAR',
        startDate: periodStart,
        endDate: periodEnd,
        payrollDate: periodEnd,
        status: 'DRAFT',
        createdById: superAdmin.id
      }
    });

    for (let i = 0; i < 5; i++) {
      const worker = workers[i];
      await prisma.payroll.create({
        data: {
          payrollPeriodId: payrollPeriod.id,
          workerId: worker.id,
          projectId: project.id,
          basicPay: 5000 + (i * 500),
          grossPay: 5000 + (i * 500),
          netPay: 4800 + (i * 500),
          paymentStatus: 'PENDING'
        }
      });
    }
  }

  console.log('--- DEMO DATA SEED COMPLETE ---');
}

// Allow script execution directly
if (require.main === module) {
  seedDemoData()
    .then(() => prisma.$disconnect())
    .catch((error) => {
      console.error(error);
      prisma.$disconnect();
      process.exit(1);
    });
}
