import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedKnowledgeCenter() {
  console.log('--- SEEDING KNOWLEDGE CENTER ---');
  
  const masterMaterialsSOP = `
# Master Materials List Consolidation SOP & Validation Rules

## Overview
The Master Materials List is generated by consolidating all items from the **Procurement Benchmark (Forecast BOQ)**, NOT the Awarded BOQ. This ensures procurement is strictly guided by the finalized budget baseline. The AI Engine groups identical items to prevent duplicate material requests and ensure uniform procurement pricing.

## Functionalities & Validation Rules
1. **Fuzzy Name Matching**:
   - The engine strips all non-alphanumeric characters (spaces, dashes, etc.) and compares the core string in lowercase.
   - Example: "Portland Cement (40kg)" matches "portlandcement40kg".
2. **Hardcoded Overrides**:
   - Specific items like '5.0m pump Lift' or 'BDU513A450VE' must be strictly mapped and grouped under 'ACU PUMPS'.
3. **Unit Normalization**:
   - If one variation of the item uses "pc" or "pcs" and another uses a different variation, the master unit defaults to "pc".
   - If the item is marked as a "lot", the consolidated master quantity is forced to 1. Otherwise, the quantities of all matching items are summed together.
4. **Unit Cost Averaging**:
   - The Master Unit Cost is a weighted average calculated as: \`Total Cost of all mapped items / Total Summed Quantity\`.
5. **Prisma Transaction Safety**:
   - The entire consolidation process must be wrapped in a single \`$transaction\` block.
   - **Crucial Rule**: Because thousands of BOQ item mappings (\`bOQMapping\`) are created simultaneously, the transaction MUST have an extended timeout (e.g., \`{ maxWait: 10000, timeout: 120000 }\`) to prevent Prisma from timing out and throwing a \`Transaction not found\` error.
6. **Project Lock Requirement**:
   - Consolidation can ONLY happen if the Procurement Benchmark is officially locked (\`procurementBenchmarkLocked: true\`).
`;

  const accessRightsMatrix = `
# System Access Rights & Role Permissions Matrix

## Project-Based Access Control (PBAC)
1. **Project Manager (PM)**: 
   - Can approve Material Requests.
   - Can review Progress Billings.
   - Can approve Job Order payments.
2. **Project Engineer / Site Engineer**:
   - Can draft Material Requests (must select correct Benchmark BOQ item).
   - Can log Accomplishments.
3. **Purchasing Officer**:
   - Can canvass suppliers.
   - Can draft Purchase Orders (POs) and must attach the Canvass PDF.
4. **Site Admin / Site Accountant**:
   - Can upload Daily Time Records (DTRs).
   - Can encode direct expenses.
   - Can dispense Petty Cash.
5. **Finance Officer**:
   - Can approve direct expenses (relying on AI validation for duplicates).
   - Can record supplier payables (upon Delivery Receipt confirmation).
6. **Executive / Project Director**:
   - Can view Executive Dashboard across all projects.
   - Can approve high-value POs and Subcontracts.
   - Has access to AI RAG Command Center.
`;

  const masterResetInstructions = `
# Database Master Reset Protocol & Safety Instructions

## Overview
A "Master Reset" is a destructive database operation that wipes all existing transactions and restores the system to a clean state.

## Safe Reset Procedure
1. Execute \`npm run clear:seed\` to safely purge ONLY dummy seed data (workers, suppliers, subcontractors) without dropping the schema.
2. **Full Database Wipe**: If a total wipe is required (e.g., \`npx prisma migrate reset\` or \`npx prisma db push --force-reset\`), the system MUST automatically re-run \`prisma/seed.ts\`.
3. **Crucial Protection**: This Knowledge Center seeder (\`seed-knowledge-center.ts\`) MUST be explicitly invoked inside \`prisma/seed.ts\` so that all functional rules (like this one) are instantly rebuilt.
4. Never execute a destructive command in the Vercel production build script. All schema mutations must be manually approved or handled via explicit migrations (\`prisma migrate deploy\`).
`;

  const records = [
    {
      title: 'SOP: Master Materials List Consolidation AI Engine',
      description: 'Rules and functionalities for auto-consolidating BOQ items into the Master Materials List.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.1',
      summary: masterMaterialsSOP,
      tags: 'boq, procurement, consolidation, ai, rules, mandatory'
    },
    {
      title: 'SOP: Access Rights & Role Matrix',
      description: 'System roles and their exact PBAC access limits.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: accessRightsMatrix,
      tags: 'pbac, rbac, roles, permissions, mandatory'
    },
    {
      title: 'SOP: Database Master Reset Protocol & System Restore',
      description: 'Instructions for non-destructive functional restoration and hard wipes. Restricted to Superadmin.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v2.0',
      summary: `
# Database Master Reset Protocol & System Restore

## ⚠️ RESTRICTED TO SUPERADMIN ONLY ⚠️

### 1. Non-Destructive System Restore (Antigravity Command)
If functional rules, SOPs, access rights, or AI instructions go missing or get corrupted, you can trigger a **Non-Destructive Restore**.
**Command**: Ask the AI Assistant to "Run the system_restore skill" or "Trigger master restore".
**Action**: The AI will execute \`npx tsx prisma/seeders/seed-knowledge-center.ts\`.
**Safety**: This ONLY repopulates system logic and Knowledge Records. It **DOES NOT** erase or modify any live user transaction data (e.g., job orders, accomplishments, material requests) performed on the online app.

### 2. Destructive Reset (Erasing Processed Data)
If a total hard wipe is needed to erase all processed data (distinct from the functional rules):
- Use \`npm run clear:seed\` to clear dummy data only.
- Use \`npx prisma migrate reset\` to wipe everything to zero.
**Safety**: Hard wipes should generally only be done on the local app, NOT the online production app.
- Pushing to GitHub/Vercel will only push functional code/data and will safely preserve the online app's live database transactions.
`,
      tags: 'reset, database, seed, mandatory, superadmin, restore, antigravity'
    },
    {
      title: 'SOP: Project Scheduling & AI Simulation',
      description: 'Rules for AI-assisted scheduling, boundary clamping, and phase summarization.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v2.0',
      summary: '# Project Scheduling Rules\n1. AI generated activities must strictly adhere to project start and end dates (Boundary Clamping).\n2. Activities must be wrapped in batch Prisma transactions to prevent timeouts.\n3. The Phase Summary view must aggregate data hierarchically.\n\n## Advanced AI Simulation Rules\n4. **High Granularity Phasing:** The AI must generate 8 to 15 detailed construction sub-phases based on industry standards (e.g. Substructure, MEPF, Architectural Finishes) instead of simple generic blocks.\n5. **Strict BOQ Material Balancing:** Every single Awarded BOQ material ID must be assigned to exactly one phase. No BOQ item can be left unassigned, ensuring the schedule Grand Total matches the Awarded Contract Amount.\n6. **Manual Override Safety:** During an AI re-simulation, existing activities that have manual overrides (e.g., actualProgressPercent > 0, or status modified by a user) MUST be preserved. The AI will not overwrite real-world progress.\n7. **Auto-Commencement:** If a scheduled activity start date is in the past, the system automatically sets its `actualStartDate` and marks it `IN_PROGRESS` (or `COMPLETED` if time has lapsed).',
      tags: 'scheduling, ai, simulation, mandatory'
    },
    {
      title: 'SOP: Variation Orders (VO)',
      description: 'Rules for processing subcontractor and client variation orders.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# Variation Orders\n1. VOs require justification from the PM.\n2. Approvals must go through the Executive Dashboard if they exceed budget thresholds.\n3. Costs are drawn from the benchmark BOQ if available.',
      tags: 'vo, variation, orders, mandatory'
    },
    {
      title: 'SOP: Subcontracting',
      description: 'Rules for subcontract packaging, billing, and progress evaluation.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# Subcontracting\n1. Subcontractors must be seeded into the system before packaging.\n2. Progress Billings must be matched against physical site accomplishments (photos required).\n3. Payments are routed to the Finance Officer.',
      tags: 'subcontracting, billing, mandatory'
    },
    {
      title: 'SOP: Security Operations Center (SOC)',
      description: 'Rules for system security, audit logging, and RBAC.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# Security Operations Center\n1. Every action is logged in the Audit Trail.\n2. Access is governed by the PBAC (Project-Based Access Control) system context headers.\n3. Drafts and simulated roles are heavily restricted.',
      tags: 'security, soc, audit, mandatory'
    },
    {
      title: 'SOP: Equipment & Fleet Management',
      description: 'Rules for GPS webhooks, utilization tracking, and maintenance.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# Equipment Management\n1. Heavy equipment logs rely on incoming Hikvision/Geotab GPS webhooks.\n2. Utilization logs must tie back to specific project job orders.\n3. Maintenance schedules are calculated based on engine hours.',
      tags: 'equipment, fleet, gps, mandatory'
    },
    {
      title: 'SOP: ERP Assistant (JBurns AI)',
      description: 'Rules for the Live Database RAG system and chatbot integration.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# ERP Assistant\n1. Uses a 5-step semantic pipeline (Intent -> Expansion -> PBAC/RBAC -> Multi-Search -> Compare/Summarize).\n2. Adheres to the Master Ontology for database term mapping.\n3. Automatically applies PBAC restrictions so users only query allowed projects.',
      tags: 'ai, assistant, chatbot, rag, mandatory'
    },
    {
      title: 'SOP: OpenAI & Gemini Provider Settings',
      description: 'Rules for multi-model AI orchestration.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: '# AI Providers\n1. @google/genai is primarily used for structured JSON scheduling tasks.\n2. @ai-sdk/openai is leveraged for semantic extraction and Chat UI.\n3. Both require valid environment variables securely configured on Vercel.',
      tags: 'openai, gemini, ai, settings, mandatory'
    }
  ];

  for (const record of records) {
    // Upsert to ensure we don't duplicate on multiple runs, using title as a unique identifier if possible.
    // However, title is not @unique in schema. We will just check if it exists first.
    const existing = await prisma.knowledgeRecord.findFirst({
      where: { title: record.title }
    });
    
    if (existing) {
      await prisma.knowledgeRecord.update({
        where: { id: existing.id },
        data: record
      });
      console.log(`Updated existing Knowledge Record: ${record.title}`);
    } else {
      await prisma.knowledgeRecord.create({ data: record });
      console.log(`Created new Knowledge Record: ${record.title}`);
    }
  }
  
  console.log('--- KNOWLEDGE CENTER SEEDING COMPLETED ---');
}

// Allow direct execution if run as standalone script
if (require.main === module) {
  seedKnowledgeCenter()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
