import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedKnowledgeCenter() {
  console.log('--- SEEDING KNOWLEDGE CENTER ---');

  const masterMaterialsSOP = `
# Master Materials List Consolidation SOP & Validation Rules

## Overview
The Master Materials List is generated by consolidating all items from an Awarded Bill of Quantities (BOQ). The AI Engine groups identical items to prevent duplicate material requests and ensure uniform procurement pricing.

## Functionalities & Validation Rules
1. **Fuzzy Name Matching**:
   - The engine strips all non-alphanumeric characters (spaces, dashes, etc.) and compares the core string in lowercase.
   - Example: "Portland Cement (40kg)" matches "portlandcement40kg".
2. **Hardcoded Overrides**:
   - Specific items like '5.0m pump Lift' or 'BDU513A450VE' must be strictly mapped and grouped under 'ACU PUMPS'.
3. **Unit Normalization**:
   - If one variation of the item uses "pc" or "pcs" and another uses a different variation, the master unit defaults to "pc".
   - If the item is marked as a "lot", the consolidated master quantity is forced to 1. Otherwise, the quantities of all matching items are summed together.
4. **Unit Cost Averaging**:
   - The Master Unit Cost is a weighted average calculated as: \`Total Cost of all mapped items / Total Summed Quantity\`.
5. **Prisma Transaction Safety**:
   - The entire consolidation process must be wrapped in a single \`$transaction\` block.
   - **Crucial Rule**: Because thousands of BOQ item mappings (\`bOQMapping\`) are created simultaneously, the transaction MUST have an extended timeout (e.g., \`{ maxWait: 10000, timeout: 120000 }\`) to prevent Prisma from timing out and throwing a \`Transaction not found\` error.
6. **Project Lock Requirement**:
   - Consolidation can ONLY happen if the Project BOQ is officially locked (\`boqLocked: true\`).
`;

  const accessRightsMatrix = `
# System Access Rights & Role Permissions Matrix

## Project-Based Access Control (PBAC)
1. **Project Manager (PM)**:
   - Can approve Material Requests.
   - Can review Progress Billings.
   - Can approve Job Order payments.
2. **Project Engineer / Site Engineer**:
   - Can draft Material Requests (must select correct Benchmark BOQ item).
   - Can log Accomplishments.
3. **Purchasing Officer**:
   - Can canvass suppliers.
   - Can draft Purchase Orders (POs) and must attach the Canvass PDF.
4. **Site Admin / Site Accountant**:
   - Can upload Daily Time Records (DTRs).
   - Can encode direct expenses.
   - Can dispense Petty Cash.
5. **Finance Officer**:
   - Can approve direct expenses (relying on AI validation for duplicates).
   - Can record supplier payables (upon Delivery Receipt confirmation).
6. **Executive / Project Director**:
   - Can view Executive Dashboard across all projects.
   - Can approve high-value POs and Subcontracts.
   - Has access to AI RAG Command Center.
`;

  const masterResetInstructions = `
# Database Master Reset Protocol & Safety Instructions

## Overview
A "Master Reset" is a destructive database operation that wipes all existing transactions and restores the system to a clean state.

## Safe Reset Procedure
1. Execute \`npm run clear:seed\` to safely purge ONLY dummy seed data (workers, suppliers, subcontractors) without dropping the schema.
2. **Full Database Wipe**: If a total wipe is required (e.g., \`npx prisma migrate reset\` or \`npx prisma db push --force-reset\`), the system MUST automatically re-run \`prisma/seed.ts\`.
3. **Crucial Protection**: This Knowledge Center seeder (\`seed-knowledge-center.ts\`) MUST be explicitly invoked inside \`prisma/seed.ts\` so that all functional rules (like this one) are instantly rebuilt.
4. Never execute a destructive command in the Vercel production build script. All schema mutations must be manually approved or handled via explicit migrations (\`prisma migrate deploy\`).
`;

  const records = [
    {
      title: 'SOP: Master Materials List Consolidation AI Engine',
      description: 'Rules and functionalities for auto-consolidating BOQ items into the Master Materials List.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.1',
      summary: masterMaterialsSOP,
      tags: 'boq, procurement, consolidation, ai, rules, mandatory'
    },
    {
      title: 'SOP: Access Rights & Role Matrix',
      description: 'System roles and their exact PBAC access limits.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: accessRightsMatrix,
      tags: 'pbac, rbac, roles, permissions, mandatory'
    },
    {
      title: 'SOP: Database Master Reset Protocol',
      description: 'Instructions on how a master reset works and safety rules.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.0',
      summary: masterResetInstructions,
      tags: 'reset, database, seed, mandatory'
    }
  ];

  for (const record of records) {
    // Upsert to ensure we don't duplicate on multiple runs, using title as a unique identifier if possible.
    // However, title is not @unique in schema. We will just check if it exists first.
    const existing = await prisma.knowledgeRecord.findFirst({
      where: { title: record.title }
    });

    if (existing) {
      await prisma.knowledgeRecord.update({
        where: { id: existing.id },
        data: record
      });
      console.log(`Updated existing Knowledge Record: ${record.title}`);
    } else {
      await prisma.knowledgeRecord.create({ data: record });
      console.log(`Created new Knowledge Record: ${record.title}`);
    }
  }

  console.log('--- KNOWLEDGE CENTER SEEDING COMPLETED ---');
}

// Allow direct execution if run as standalone script
if (require.main === module) {
  seedKnowledgeCenter()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
