import React from 'react';
import { prisma } from '@/lib/prisma';
import Link from 'next/link';

export const metadata = {
  title: 'AI Reports Library | Executive Command Center',
};

async function getGeneratedReports() {
  return await prisma.aIGeneratedReport.findMany({
    include: {
      generatedBy: { select: { name: true } }
    },
    orderBy: { createdAt: 'desc' }
  });
}

export default async function AIReportsPage() {
  const reports = await getGeneratedReports();

  const getStatusColor = (status: string) => {
    switch(status) {
      case 'APPROVED': return { bg: '#d1fae5', text: '#065f46' };
      case 'FOR_REVIEW': return { bg: '#fef3c7', text: '#92400e' };
      case 'DRAFT': return { bg: '#f3f4f6', text: '#374151' };
      default: return { bg: '#f3f4f6', text: '#374151' };
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* Header Section */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: '1.875rem', fontWeight: 700, color: '#111827' }}>AI Report Generator & Library</h1>
          <p style={{ margin: '4px 0 0', color: '#6b7280' }}>Automatically generated executive summaries, risk reports, and evidence packs.</p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button style={{ padding: '8px 16px', backgroundColor: '#2563eb', border: 'none', borderRadius: '6px', fontWeight: 500, color: '#ffffff', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span>➕</span> Generate New Report
          </button>
        </div>
      </div>

      {/* Reports Table */}
      <div style={{ backgroundColor: '#ffffff', borderRadius: '12px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', overflow: 'hidden', border: '1px solid #e5e7eb' }}>
        {reports.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: '#6b7280' }}>
            <div style={{ fontSize: '3rem', marginBottom: '16px' }}>📄</div>
            <p>No AI reports have been generated yet.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ backgroundColor: '#f9fafb', borderBottom: '1px solid #e5e7eb' }}>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Report ID</th>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Title & Scope</th>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Status</th>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Generated By</th>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Date</th>
                  <th style={{ padding: '16px 24px', fontSize: '0.75rem', fontWeight: 600, color: '#4b5563', textTransform: 'uppercase' }}>Export</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((report, idx) => {
                  const statusColors = getStatusColor(report.status);
                  return (
                    <tr key={report.id} style={{ borderBottom: idx === reports.length - 1 ? 'none' : '1px solid #e5e7eb', backgroundColor: '#ffffff' }}>
                      <td style={{ padding: '16px 24px', fontSize: '0.875rem', color: '#6b7280', fontFamily: 'monospace' }}>
                        {report.reportCode}
                      </td>
                      <td style={{ padding: '16px 24px' }}>
                        <div style={{ fontWeight: 600, color: '#111827' }}>{report.title}</div>
                        <div style={{ fontSize: '0.75rem', color: '#6b7280', marginTop: '4px' }}>
                          {report.scopeType} {report.projectId ? `- Project ID: ${report.projectId}` : ''}
                        </div>
                      </td>
                      <td style={{ padding: '16px 24px' }}>
                        <span style={{ fontSize: '0.75rem', fontWeight: 600, padding: '4px 8px', borderRadius: '9999px', backgroundColor: statusColors.bg, color: statusColors.text }}>
                          {report.status}
                        </span>
                      </td>
                      <td style={{ padding: '16px 24px', fontSize: '0.875rem', color: '#374151' }}>
                        {report.generatedBy?.name || 'System AI'}
                      </td>
                      <td style={{ padding: '16px 24px', fontSize: '0.875rem', color: '#374151' }}>
                        {report.createdAt.toLocaleDateString()}
                      </td>
                      <td style={{ padding: '16px 24px' }}>
                        <div style={{ display: 'flex', gap: '8px' }}>
                          <button style={{ padding: '4px 8px', fontSize: '0.75rem', backgroundColor: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>PDF</button>
                          <button style={{ padding: '4px 8px', fontSize: '0.75rem', backgroundColor: '#f0fdf4', color: '#16a34a', border: '1px solid #bbf7d0', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>XLSX</button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
}
