const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, 'docs', 'azure-migration');

if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });
}

fs.writeFileSync(path.join(docsDir, '01-current-state-inventory.md'), `# Current State Inventory

## 1. Application Overview
- **Application**: OneSystemsERP
- **Frontend**: Next.js 16.2.7 (Turbopack) hosted on Vercel
- **Backend Runtime**: Vercel Server Actions (72+ action files) and Next.js Route Handlers (~70 endpoints)
- **Database**: PostgreSQL (Prisma ORM v6.19.3)
- **Storage**: AWS S3 (Client installed) and local/Vercel blobs
- **Authentication**: NextAuth 5.0.0-beta.31
- **AI Integrations**: OpenAI, Google GenAI
- **External Integrations**: Hikvision, UnionBank, Geotab FMS

## 2. Route Inventory (Sample)
| Route / Action | Current Runtime | Auth Required | Database Used | Migration Target |
|---|---|---|---|---|
| \`src/app/actions/payrollActions.ts\` | Vercel Server | Yes | \`PayrollPeriod\`, etc. | Azure Container Apps |
| \`src/app/actions/financeActions.ts\` | Vercel Server | Yes | \`Expense\`, etc. | Azure Container Apps |
| \`api/projects/[id]/scheduling/ai\` | Vercel API | Yes | \`Project\`, \`ScheduleActivity\` | Azure Container Apps |
| \`api/cron/payment-polling\` | Vercel Cron | Token | \`PayrollBankLedger\` | Azure Container Apps Scheduled Job |

## 3. Database Inventory
- **Engine**: PostgreSQL
- **Key Tables**: \`User\`, \`Project\`, \`PurchaseOrder\`, \`MaterialRequest\`, \`Expense\`, \`PettyCashAccount\`, \`KnowledgeRecord\`, \`ScheduleActivity\`
- **Audit Logging**: \`AuditLog\`, \`KnowledgeAuditTrail\`
- **Financial Integrity**: Full transactional double-entry mapping in ledgers.

## 4. Integration & Environment
- **Env Vars**: \`DATABASE_URL\`, \`DIRECT_URL\`, \`AUTH_SECRET\`, \`OPENAI_API_KEY\`, \`GEMINI_API_KEY\`, \`NEXT_PUBLIC_APP_URL\`
- **Secrets Management**: Currently in Vercel Environment Variables.
`);

fs.writeFileSync(path.join(docsDir, '02-migration-risk-register.md'), `# Migration Risk Register

## 1. Authentication Parity
**Risk**: NextAuth relies heavily on Next.js/Vercel server context. Moving business logic to Azure requires strict API token validation or JWT sharing between Vercel and Azure.
**Mitigation**: Implement strict JWT validation at the Azure API Gateway layer and ensure token signing secrets are shared securely via Azure Key Vault.

## 2. Database Concurrency during Cutover
**Risk**: If Next.js Server Actions and Azure Container Apps both write to the database simultaneously during wave migration, it could cause race conditions or corrupt financial totals.
**Mitigation**: Use strictly controlled feature flags for API rewrites. Isolate entire modules (e.g. Procurement) to route exclusively to Azure once cutover.

## 3. File Upload Proxy Bottleneck
**Risk**: Proxying large file uploads through Vercel to Azure Blob Storage might exceed Vercel's 4.5MB payload limit on serverless functions.
**Mitigation**: Implement direct-to-storage uploads via Pre-Signed URLs generated by the Azure backend.

## 4. Double-Entry Accounting Synchronization
**Risk**: If a network failure occurs between the Vercel Frontend and Azure Backend during a financial transaction approval, the UI might show failure while the backend processes it.
**Mitigation**: Enforce Idempotency Keys on all financial write operations to Azure.
`);

fs.writeFileSync(path.join(docsDir, '03-route-ownership-matrix.md'), `# Initial Route Ownership Matrix

| Route Area | Current Owner | Temporary Migration Owner | Final Owner | Rewrite Rule |
|---|---|---|---|---|
| \`/api/auth/*\` | Vercel | Vercel | Vercel | None |
| \`/api/admin/*\` | Vercel | Azure (Wave 8) | Azure | \`/api/admin/*\` -> \`api.onesystemserp.com/admin/*\` |
| \`/api/projects/*\` | Vercel | Azure (Wave 2) | Azure | \`/api/projects/*\` -> \`api.onesystemserp.com/projects/*\` |
| \`/api/ai/*\` | Vercel | Azure (Wave 7) | Azure | \`/api/ai/*\` -> \`api.onesystemserp.com/ai/*\` |
| Server Actions (\`financeActions.ts\`) | Vercel | Azure (Wave 6) | Azure | Converted to REST/RPC -> \`api.onesystemserp.com/rpc/finance/*\` |
`);

fs.writeFileSync(path.join(docsDir, '04-azure-service-mapping.md'), `# Recommended Azure Service Mapping

| Current Vercel / AWS Component | Target Azure Service | Justification |
|---|---|---|
| Next.js Server Actions / API Routes | Azure Container Apps | Serverless scaling, deep VNet integration, zero idle cost option, native Docker support. |
| Vercel Postgres (Neon) | Azure Database for PostgreSQL Flexible Server | Direct PostgreSQL compatibility, high availability, native VNet injection, Point-in-Time Restore. |
| AWS S3 / Vercel Blob | Azure Blob Storage | Native ecosystem integration, private link capability, tiered lifecycle management. |
| Vercel Cron Jobs | Azure Container Apps Jobs | Fully managed scheduled execution running the exact same container image. |
| AWS SQS / Background Jobs | Azure Service Bus | Enterprise message broker, dead-letter queues, exactly-once delivery guarantees for financial syncs. |
| Vercel Environment Variables | Azure Key Vault | Hardware security modules, managed identities, dynamic secret rotation. |
| Vercel Analytics / Logs | Azure Log Analytics + App Insights | Centralized correlation IDs, deep application performance monitoring. |
| Direct API access | Azure API Management | Optional initially, recommended for rate limiting, JWT validation, and API versioning as traffic scales. |
`);

console.log("Documents created successfully.");
