import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const projectId = 'cmriveop10378vcqsma96byxi'; // From the URL in the screenshot

  console.log("=== PROJECT & LOCKED BOQ ===");
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      awardedBOQItems: true
    }
  });
  console.log(`Project Awarded Amount: ${project?.awardedContractAmount}`);
  const boqTotal = project?.awardedBOQItems.reduce((acc, curr) => acc + curr.totalCost.toNumber(), 0);
  console.log(`Locked BOQ Lines: ${project?.awardedBOQItems.length}`);
  console.log(`Locked BOQ Total: ${boqTotal}`);

  console.log("\n=== SCHEDULES ===");
  const schedules = await prisma.projectSchedule.findMany({
    where: { projectId },
    include: {
      phases: true,
      activities: true,
      dependencies: true,
      boqAllocations: true
    }
  });
  console.log(`Found ${schedules.length} schedules.`);
  for (const s of schedules) {
    console.log(`- ID: ${s.id} | Name: ${s.name} | Status: ${s.status}`);
    console.log(`  Awarded: ${s.awardedContractAmount} | Scheduled: ${s.scheduledAmount}`);
    console.log(`  Phases: ${s.phases.length} | Activities: ${s.activities.length}`);
    console.log(`  Dependencies: ${s.dependencies.length} | BOQ Allocs: ${s.boqAllocations.length}`);
    console.log(`  Created: ${s.createdAt} | Updated: ${s.updatedAt}`);
  }

  console.log("\n=== GENERATION AUDITS ===");
  const audits = await prisma.scheduleGenerationAudit.findMany({
    where: { projectId },
    orderBy: { responseTimestamp: 'desc' },
    take: 3
  });
  
  for (const a of audits) {
    console.log(`- Audit ID: ${a.id} | Status: ${a.resultStatus}`);
    console.log(`  Time: ${a.responseTimestamp}`);
    const res = JSON.parse(a.validationResults || '{}');
    if (res.error) console.log(`  Error: ${res.error}`);
    if (res.validationStatus) console.log(`  ValidationStatus: ${JSON.stringify(res.validationStatus)}`);
    if (res.aiProposal) console.log(`  Phases generated by AI: ${res.aiProposal.phases.length}`);
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
