import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const content = `
# Master Materials List Consolidation SOP & Validation Rules

## Overview
The Master Materials List is generated by consolidating all items from an Awarded Bill of Quantities (BOQ). The AI Engine groups identical items to prevent duplicate material requests and ensure uniform procurement pricing.

## Functionalities & Validation Rules
1. **Fuzzy Name Matching**:
   - The engine strips all non-alphanumeric characters (spaces, dashes, etc.) and compares the core string in lowercase.
   - Example: "Portland Cement (40kg)" matches "portlandcement40kg".
2. **Hardcoded Overrides**:
   - Specific items like '5.0m pump Lift' or 'BDU513A450VE' must be strictly mapped and grouped under 'ACU PUMPS'.
3. **Unit Normalization**:
   - If one variation of the item uses "pc" or "pcs" and another uses a different variation, the master unit defaults to "pc".
   - If the item is marked as a "lot", the consolidated master quantity is forced to 1. Otherwise, the quantities of all matching items are summed together.
4. **Unit Cost Averaging**:
   - The Master Unit Cost is a weighted average calculated as: \`Total Cost of all mapped items / Total Summed Quantity\`.
5. **Prisma Transaction Safety**:
   - The entire consolidation process must be wrapped in a single \`$transaction\` block.
   - **Crucial Rule**: Because thousands of BOQ item mappings (\`bOQMapping\`) are created simultaneously, the transaction MUST have an extended timeout (e.g., \`{ maxWait: 10000, timeout: 120000 }\`) to prevent Prisma from timing out and throwing a \`Transaction not found\` error.
6. **Project Lock Requirement**:
   - Consolidation can ONLY happen if the Project BOQ is officially locked (\`boqLocked: true\`).
`;

  await prisma.knowledgeRecord.create({
    data: {
      title: 'SOP: Master Materials List Consolidation AI Engine',
      description: 'Rules and functionalities for auto-consolidating BOQ items into the Master Materials List.',
      notebookType: 'SOP',
      documentType: 'Markdown',
      status: 'Approved',
      version: 'v1.1',
      summary: content,
      tags: 'boq, procurement, consolidation, ai, rules'
    }
  });

  console.log('Successfully inserted Master Materials SOP into Knowledge Center!');
}

main()
  .catch(e => console.error(e))
  .finally(() => prisma.$disconnect());
