import { prisma } from '@/lib/prisma';
import { notFound } from 'next/navigation';
import PrintButton from './PrintButton';

export const dynamic = 'force-dynamic';

export default async function PrintableDeliveryRecord({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = await params;
  const delivery = await prisma.delivery.findUnique({
    where: { id: resolvedParams.id },
    include: {
      po: { include: { supplier: true, mr: { include: { project: true } } } },
      items: { include: { consolidatedBoqItem: true } },
      receivedBy: true,
      approvedBy: true,
    }
  });

  if (!delivery) {
    return <div>Delivery not found. ID requested: {resolvedParams.id}</div>;
  }
  
  if (delivery.status !== 'APPROVED') {
    return <div>Delivery is not approved. Current status: {delivery.status}</div>;
  }

  return (
    <div style={{
      background: 'white',
      color: 'black',
      minHeight: '100vh',
      padding: '40px',
      fontFamily: '"Inter", "Roboto", "Helvetica Neue", Arial, sans-serif'
    }}>
      <div style={{ maxWidth: '800px', margin: '0 auto', border: '1px solid #ddd', padding: '40px', boxShadow: '0 0 20px rgba(0,0,0,0.05)' }}>
        
        {/* Print Button (Hidden in Print) */}
        <div style={{ textAlign: 'right', marginBottom: '20px' }}>
          <PrintButton />
        </div>

        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '40px', borderBottom: '2px solid #000', paddingBottom: '20px' }}>
          <h1 style={{ margin: '0 0 10px 0', fontSize: '24px', textTransform: 'uppercase', letterSpacing: '2px' }}>
            Official Delivery Record
          </h1>
          <p style={{ margin: 0, color: '#555', fontSize: '14px' }}>Generated by OneSystemsErp Procurement System</p>
        </div>

        {/* Mismatch Flag */}
        {delivery.isMismatch && (
          <div style={{ border: '2px solid #000', padding: '15px', marginBottom: '30px', background: '#f9f9f9' }}>
            <h3 style={{ margin: '0 0 10px 0', textTransform: 'uppercase' }}>⚠️ Notice of Discrepancy</h3>
            <p style={{ margin: 0, fontStyle: 'italic' }}>{delivery.mismatchNotes}</p>
          </div>
        )}

        {/* Metadata */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '40px', fontSize: '14px' }}>
          <div>
            <p style={{ margin: '0 0 8px 0' }}><strong>Delivery Receipt No:</strong> {delivery.receiptNumber}</p>
            <p style={{ margin: '0 0 8px 0' }}><strong>Purchase Order:</strong> {delivery.po.poNumber}</p>
            <p style={{ margin: '0 0 8px 0' }}><strong>Supplier:</strong> {delivery.po.supplier.name}</p>
          </div>
          <div>
            <p style={{ margin: '0 0 8px 0' }}><strong>Project:</strong> {delivery.po.mr.project.name}</p>
            <p style={{ margin: '0 0 8px 0' }}><strong>Date Received:</strong> {new Date(delivery.createdAt).toLocaleDateString()}</p>
            <p style={{ margin: '0 0 8px 0' }}><strong>Date Approved:</strong> {new Date(delivery.updatedAt).toLocaleDateString()}</p>
          </div>
        </div>

        {/* Table */}
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '40px', fontSize: '14px' }}>
          <thead>
            <tr style={{ background: '#f0f0f0' }}>
              <th style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'left' }}>Item Description</th>
              <th style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'center' }}>DR Qty</th>
              <th style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'center' }}>Actual Qty</th>
              <th style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'left' }}>Remarks</th>
            </tr>
          </thead>
          <tbody>
            {delivery.items.map(item => (
              <tr key={item.id}>
                <td style={{ border: '1px solid #ccc', padding: '10px' }}>{item.consolidatedBoqItem.description}</td>
                <td style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'center' }}>{item.drQuantity !== null ? item.drQuantity : 'N/A'}</td>
                <td style={{ border: '1px solid #ccc', padding: '10px', textAlign: 'center', fontWeight: 'bold' }}>{item.quantity}</td>
                <td style={{ border: '1px solid #ccc', padding: '10px' }}>{item.remarks || '-'}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Signatures */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px', marginTop: '60px' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ borderBottom: '1px solid #000', marginBottom: '10px', height: '40px', display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}>
              {delivery.receivedBy?.name}
            </div>
            <p style={{ margin: 0, fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase' }}>Received & Encoded By (Stockman)</p>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ borderBottom: '1px solid #000', marginBottom: '10px', height: '40px', display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}>
              {delivery.approvedBy?.name}
            </div>
            <p style={{ margin: 0, fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase' }}>Verified & Approved By (Accountant)</p>
          </div>
        </div>

      </div>

      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; }
        }
      `}} />
    </div>
  );
}
